apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/riccardoforzan/flux-test
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-root
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-repo
  targetNamespace: flux-system
