apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 1m
  releaseName: mongodb
  targetNamespace: mongodb
  chart:
    spec:
      chart: community-operator
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
