apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-namespace
  namespace: flux-system
spec:
  interval: 1m
  path: ./mongodb/namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-repo
